import streamlit as st

st.markdown("**Top 10 Stock Market Listed Companies**")
# st.subheader("Top 10 Stock Market Listed Companies")
left_col, right_col = st.columns(2)
left_col.write("**Company Name**")
right_col.write("**Ticker Symbol**")
left_col.write("Reliance Industries Limited")
right_col.write("RELIANCE.NS")
left_col.write("State Bank of India")
right_col.write("SBIN.NS")
left_col.write("HDFC Bank Limited")
right_col.write("HDFCBANK.NS")
left_col.write("Axis Bank Limited")
right_col.write("AXISBANK.NS")
left_col.write("Tata Consultancy Services Limited")
right_col.write("TCS.NS")
left_col.write("Infosys Limited")
right_col.write("INFY")
left_col.write("Wipro Limited")
right_col.write("WIT")
left_col.write("Sun Pharmaceutical Industries Limited")
right_col.write("SUNPHARMA.NS")
left_col.write("Cipla Limited ")
right_col.write("CIPLA.NS")
left_col.write("UltraTech Cement Limited ")
right_col.write("ULTRACEMCO.NS")
